assignment1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog'))
]

blog/urls.py
from django.urls import path

from blog.views import blog_view, author_view, home_view

app_name = 'blog'

urlpatterns = [
    path('view/', blog_view, name='view'),
    path('author/<int:id>', author_view),
    path('', home_view, name='home'),

]

blog/models.py
from django.db import models
from django.utils import timezone


class AuthorTable(models.Model):
    name = models.CharField(max_length=150)
    email = models.EmailField()
    address = models.CharField(max_length=150)

    def __str__(self):
        return self.name


class BlogTable(models.Model):
    author = models.ForeignKey(AuthorTable, on_delete=models.CASCADE)
    blog = models.TextField(max_length=500)
    created_at = models.DateField(default=timezone.now)
    updated_at = models.DateField(blank=True)

    def __str__(self):
        return str(self.id)

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import BlogTable, AuthorTable

app_name = 'blog'


def home_view(request):
    return render(request, 'blog/home.html')


def blog_view(request):
    obj = BlogTable.objects.all()
    return render(request, 'blog/blog.html', {'obj': obj})


def author_view(request, id):
    obj1 = get_object_or_404(AuthorTable, id=id)
    return render(request, 'blog/author.html', {'obj1': obj1})

blog/templates/blog/author.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Author</title>
    <link rel="stylesheet" href="{% static 'blog/author.css'%}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
<div class="back font">
    <a href="{% url 'blog:view' %} ">Back</a>
</div>

<div class="card font">
  <h1 class="name">{{obj1.name}}</h1>
  <p class="email">{{obj1.email}}</p>
  <p class="address">{{obj1.address}}</p>
  <a href="#"><i class="fa fa-dribbble"></i></a>
  <a href="#"><i class="fa fa-twitter"></i></a>
  <a href="#"><i class="fa fa-linkedin"></i></a>
  <a href="#"><i class="fa fa-facebook"></i></a>
  <p><button>Contact</button></p>
</div>

</body>
</html>

blog/templates/blog/blog.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blogs</title>
    <link rel="stylesheet" type="text/css" href="{% static 'blog/blo.css' %}" />

</head>
<body>

<div class="home font">
    <a href="{% url 'blog:home' %}">Home</a>
</div>

<div class="tab">
    <table class="font">
    <tr>
        <th>ID</th>
        <th>Blog</th>
        <th>Created at</th>
        <th>Updated at</th>
        <th>Author</th>
    </tr>
    {%for i in obj%}
    <tr>
        <td>{{i.id}}</td>
        <td>{{i.blog}}</td>
        <td>{{i.created_at}}</td>
        <td>{{i.updated_at}}</td>
        <td>
            {{i.author.name}}|
            <a href="/author/{{i.id}}" class="link font">Details</a>
        </td>
    </tr>
    {%endfor%}
</table>
</div>

</body>
</html>

blog/templates/blog/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    <link rel="stylesheet" type="text/css" href="{% static 'blog/home.css' %}" />
</head>
<body>
<h1>“Blogging is a conversation, not a code.”</h1>
<div class="blog">
    <a href="/view/" >READ BLOGS</a>
</div>

</body>
</html>